version: '3'
services:
    app:
        image: kaangiray26/forte:1.3
        ports:
            - "80:80"
            - "443:443"
            - "3000:3000"
        depends_on:
            - postgres
        environment:
            # Set mode to local to run locally, or public to run publically
            # mode defaults to local
            mode: local
            forte_server: host.buzl.uk
            forte_email: kaangiray26@protonmail.com
        volumes:
            - /home/f34rl00/Music/CD:/library
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: forte
            POSTGRES_USER: forte
            POSTGRES_PASSWORD: forte
        volumes:
            - db-data:/var/lib/postgresql/data
volumes:
    db-data: