version: '3'
services:
    app:
        image: kaangiray26/forte:1.3
        ports:
            - "80:80"
            - "443:443"
            - "3000:3000"
        depends_on:
            - postgres
        environment:
            mode: local
            forte_server: <server>
            forte_email: <email>
        volumes:
            - <library>:/library
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: forte
            POSTGRES_USER: forte
            POSTGRES_PASSWORD: forte
        volumes:
            - db-data:/var/lib/postgresql/data
volumes:
    db-data: