version: '3'
services:
    app:
        image: kaangiray26/forte:1.6
        ports:
            - "80:80"
            - "443:443"
            - "3000:3000"
        depends_on:
            postgres:
                condition: service_healthy
        environment:
            mode: local
            forte_server: <server>
            forte_email: <email>
            POSTGRES_HOST: # Postgres Host/IP
            POSTGRES_PORT: # Postgres Database Port (Default=5432)
            POSTGRES_DB: # Set Postgres Database Name
            POSTGRES_USER: # Set Postgres Username
            POSTGRES_PASSWORD: # Set Postgres Password
            
       volumes:
            - <library>:/library
    postgres:
        image: kaangiray26/postgres:1.0
        restart: always
        environment:
            POSTGRES_DB: # Set Postgres Database Name
            POSTGRES_USER: # Set Postgres Username
            POSTGRES_PASSWORD: # Set Postgres Password
        volumes:
            - db-data:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U forte" ]
            interval: 10s
            timeout: 5s
            retries: 5
volumes:
    db-data:
