version: '3'
services:
    app:
        image: kaangiray26/forte:1.4
        ports:
            - "80:80"
            - "443:443"
            - "3000:3000"
        depends_on:
            postgres:
                condition: service_healthy
        environment:
            mode: local
            forte_server: <server>
            forte_email: <email>
        volumes:
            - <library>:/library
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: forte
            POSTGRES_USER: forte
            POSTGRES_PASSWORD: forte
        volumes:
            - db-data:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U forte" ]
            interval: 10s
            timeout: 5s
            retries: 5
volumes:
    db-data: