version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - db
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: forte
            POSTGRES_DB: forte
        volumes:
            - db-data:/var/lib/postgresql/data
volumes:
    db-data: